# **DATA LOAD**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [7]:
from google.colab import files
import zipfile
import os

# Upload Amazon Prime ZIP file
uploaded = files.upload()

Saving Amazon_prime.zip to Amazon_prime (1).zip

In [4]:
os.listdir('amazon_prime_data')

['titles.csv', 'credits.csv']

In [8]:
import zipfile

zip = zipfile.ZipFile('Amazon_prime.zip')
zip.extractall('amazon_data')

In [9]:
import pandas as pd

titles = pd.read_csv('amazon_data/titles.csv')

credits = pd.read_csv('amazon_data/credits.csv')

In [10]:
titles.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.2,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['romance', 'war', 'drama']",['US'],NaN,tt0036868,8.1,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,tt0032599,7.8,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"['thriller', 'drama', 'romance']",['US'],NaN,tt0042593,7.9,30924.0,8.273,7.6

In [11]:
credits.head()

   person_id       id           name      character   role
0      59401  ts20945     Joe Besser            Joe  ACTOR
1      31460  ts20945     Moe Howard            Moe  ACTOR
2      31461  ts20945     Larry Fine          Larry  ACTOR
3      21174  tm19248  Buster Keaton    Johnny Gray  ACTOR
4      28713  tm19248    Marion Mack  Annabelle Lee  ACTOR

# **DATA EXPLORATION**

In [12]:
print("Titles:", titles.shape)
print("Credits:", credits.shape)

Titles: (9871, 15)
Credits: (124235, 5)

In [13]:
titles.columns

Index(['id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'seasons', 'imdb_id', 'imdb_score', 'imdb_votes', 'tmdb_popularity',
       'tmdb_score'],
      dtype='object')

In [14]:
credits.columns

Index(['person_id', 'id', 'name', 'character', 'role'], dtype='object')

In [15]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9871 entries, 0 to 9870
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    9871 non-null   object
 1   title                 9871 non-null   object
 2   type                  9871 non-null   object
 3   description           9752 non-null   object
 4   release_year          9871 non-null   int64
 5   age_certification     3384 non-null   object
 6   runtime               9871 non-null   int64
 7   genres                9871 non-null   object
 8   production_countries  9871 non-null   object
 9   seasons               1357 non-null   float64
 10  imdb_id               9204 non-null   object
 11  imdb_score            8850 non-null   float64
 12  imdb_votes            8840 non-null   float64
 13  tmdb_popularity       9324 non-null   float64
 14  tmdb_score            7789 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 1.1+ MB

In [16]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124235 entries, 0 to 124234
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   person_id  124235 non-null  int64
 1   id         124235 non-null  object
 2   name       124235 non-null  object
 3   character  107948 non-null  object
 4   role       124235 non-null  object
dtypes: int64(1), object(4)
memory usage: 4.7+ MB

In [17]:
titles.isnull().sum()

id                         0
title                      0
type                       0
description              119
release_year               0
age_certification       6487
runtime                    0
genres                     0
production_countries       0
seasons                 8514
imdb_id                  667
imdb_score              1021
imdb_votes              1031
tmdb_popularity          547
tmdb_score              2082
dtype: int64

In [18]:
credits.isnull().sum()

person_id        0
id               0
name             0
character    16287
role             0
dtype: int64

In [19]:
titles.duplicated().sum()

np.int64(3)

In [20]:
credits.duplicated().sum()

np.int64(56)

# **DATA CLEANING**

**1. Remove duplicates from Titles**

In [55]:
titles = titles.drop_duplicates()
print("Duplicates:", titles.duplicated().sum())

Duplicates: 0

**2. Remove duplicates from Credits**

In [22]:
credits = credits.drop_duplicates()

print("Duplicates:", credits.duplicated().sum())

Duplicates: 0

**3. Fill missing descriptions**

In [23]:
titles['description'] = titles['description'].fillna('No Description')

**4. Fill missing Age Certification**

In [24]:
titles['age_certification'] = titles['age_certification'].fillna('Not Rated')

In [25]:
shows = titles[titles['type'] == 'SHOW']

**5. IMDb Score and IMDb Votes**

In [56]:
rating_data = titles.dropna(subset=['imdb_score'])

**6. Clean missing Character in Credits**

In [26]:
credits['character'] = credits['character'].fillna('Unknown')

**7. Check cleaning**

In [27]:
titles.isnull().sum()

id                         0
title                      0
type                       0
description                0
release_year               0
age_certification          0
runtime                    0
genres                     0
production_countries       0
seasons                 8511
imdb_id                  667
imdb_score              1021
imdb_votes              1031
tmdb_popularity          547
tmdb_score              2080
dtype: int64

In [28]:
credits.isnull().sum()

person_id    0
id           0
name         0
character    0
role         0
dtype: int64

In [29]:
print("Titles duplicates:", titles.duplicated().sum())
print("Credits duplicates:", credits.duplicated().sum())

Titles duplicates: 0
Credits duplicates: 0

# **Exploratory Data Analysis**

**Total Titles**

In [30]:
titles['id'].nunique()

9868

**Movies vs TV Shows**

In [31]:
titles['type'].value_counts()

type
MOVIE    8511
SHOW     1357
Name: count, dtype: int64

**Average IMDb Rating**

In [32]:
titles['imdb_score'].mean()

np.float64(5.976534418446931)

**Average TMDB Score**

In [33]:
round(titles['tmdb_score'].mean(), 2)

np.float64(5.98)

**Average Runtime**

In [34]:
round(titles['runtime'].mean(), 2)

np.float64(85.98)

**Oldest and Newest Content**

In [35]:
print("Oldest Release:", titles['release_year'].min())
print("Newest Release:", titles['release_year'].max())

Oldest Release: 1912
Newest Release: 2022

**Top 10 Highest-Rated Titles**

In [36]:
top_rated = titles.sort_values(
    'imdb_score',
    ascending=False
).head(10)

top_rated[['title', 'type', 'release_year', 'imdb_score']]

                              title   type  release_year  imdb_score
9135                     Pawankhind  MOVIE          2022         9.9
7783      Water Helps the Blood Run   SHOW          2019         9.7
9108              Couple of Mirrors   SHOW          2021         9.5
7422                     The Chosen   SHOW          2019         9.4
9423                     Tari Sathe  MOVIE          2021         9.4
9573              Pazhagiya Naatkal  MOVIE          2021         9.3
5113          Subaru Launch Control   SHOW          2013         9.3
9052                       Jai Bhim  MOVIE          2021         9.3
5218         A Promise to My Father  MOVIE          2013         9.2
6358  Surgeons: At the Edge of Life   SHOW          2018         9.2

**Top 10 Most Popular Titles**

In [37]:
popular = titles.sort_values(
    'tmdb_popularity',
    ascending=False
).head(10)

popular[['title', 'type', 'tmdb_popularity']]

                                  title   type  tmdb_popularity
8934                 All the Old Knives  MOVIE         1437.906
9040                             Harina   SHOW          951.863
9039                  The eighth clause  MOVIE          950.986
8964  Hotel Transylvania: Transformania  MOVIE          934.545
7421                 Sonic the Hedgehog  MOVIE          893.650
8948           Clifford the Big Red Dog  MOVIE          482.744
9092                    Queen of Spades  MOVIE          429.802
9011                            Meander  MOVIE          389.431
4099                              Suits   SHOW          356.533
5287                   Better Call Saul   SHOW          352.657

**Most Common Age Certifications**

In [38]:
titles['age_certification'].value_counts().head(10)

age_certification
Not Rated    6484
R            1249
PG-13         588
PG            582
G             269
TV-MA         217
TV-14         188
TV-PG          91
TV-Y           78
TV-G           57
Name: count, dtype: int64

**Releases by Year**

In [39]:
titles['release_year'].value_counts().sort_index()

release_year
1912      1
1914      2
1915      5
1916      2
1917      1
       ...
2018    685
2019    807
2020    698
2021    856
2022     89
Name: count, Length: 110, dtype: int64

**Movie Runtime**

In [40]:
movies = titles[titles['type'] == 'MOVIE']

**TV Show Seasons**

In [42]:
shows = titles[titles['type'] == 'SHOW']

**Top 10 Actors**

In [43]:
actors = credits[credits['role'] == 'ACTOR']

actors['name'].value_counts().head(10)

name
George 'Gabby' Hayes    49
Roy Rogers              45
Bess Flowers            44
Gene Autry              40
Nassar                  37
Herman Hack             35
Charles King            35
George Morrell          34
Earl Dwire              34
Forrest Taylor          34
Name: count, dtype: int64

**Top 10 Directors**

In [44]:
directors = credits[credits['role'] == 'DIRECTOR']

directors['name'].value_counts().head(10)

name
Joseph Kane           41
Sam Newfield          38
Jay Chapman           34
Lesley Selander       22
John English          21
Harry L. Fraser       21
William Nigh          20
Manny Rodriguez       17
Robert N. Bradbury    17
George Archainbaud    16
Name: count, dtype: int64

# **Data Visualization**

**Movies vs TV Shows**

In [45]:
type_count = titles['type'].value_counts()

fig = px.pie(
    values=type_count.values,
    names=type_count.index,
    title='Movies vs TV Shows'
)

fig.show()

**Content Released by Year**

In [46]:
year_count = titles['release_year'].value_counts().sort_index()

fig = px.line(
    x=year_count.index,
    y=year_count.values,
    title='Content Released by Year'
)

fig.update_layout(
    xaxis_title='Release Year',
    yaxis_title='Number of Titles'
)

fig.show()

**IMDb Rating Distribution**

In [47]:
fig = px.histogram(
    titles,
    x='imdb_score',
    title='IMDb Rating Distribution'
)

fig.show()

**Average IMDb Rating — Movies vs Shows**

In [48]:
rating = titles.groupby('type')['imdb_score'].mean().reset_index()

fig = px.bar(
    rating,
    x='type',
    y='imdb_score',
    title='Average IMDb Rating by Content Type'
)

fig.show()

**Top 10 Highest-Rated Titles**

In [49]:
fig = px.bar(
    top_rated,
    x='imdb_score',
    y='title',
    orientation='h',
    title='Top 10 Highest Rated Titles'
)

fig.show()

**Top 10 Most Popular Titles**

In [50]:
fig = px.bar(
    popular,
    x='tmdb_popularity',
    y='title',
    orientation='h',
    title='Top 10 Most Popular Titles'
)

fig.show()

**Movie Runtime Distribution**

In [51]:
fig = px.histogram(
    movies,
    x='runtime',
    title='Movie Runtime Distribution'
)

fig.update_layout(
    xaxis_title='Runtime in Minutes',
    yaxis_title='Number of Movies'
)

fig.show()

**Age Certification**

In [52]:
age = titles['age_certification'].value_counts().head(10)

fig = px.bar(
    x=age.index,
    y=age.values,
    title='Top Age Certifications'
)

fig.update_layout(
    xaxis_title='Age Certification',
    yaxis_title='Number of Titles'
)

fig.show()

**Top 10 Actors**

In [53]:
top_actors = actors['name'].value_counts().head(10)

fig = px.bar(
    x=top_actors.values,
    y=top_actors.index,
    orientation='h',
    title='Top 10 Actors'
)

fig.update_layout(
    xaxis_title='Number of Appearances',
    yaxis_title='Actor'
)

fig.show()

**Top 10 Directors**

In [54]:
top_directors = directors['name'].value_counts().head(10)

fig = px.bar(
    x=top_directors.values,
    y=top_directors.index,
    orientation='h',
    title='Top 10 Directors'
)

fig.update_layout(
    xaxis_title='Number of Titles',
    yaxis_title='Director'
)

fig.show()

# **Business Insights & Conclusion**

**Business Insights**


1. Movies make up the majority of Amazon Prime's content compared with TV shows.

2. The release-year analysis shows that Amazon Prime has a large amount of relatively recent content, while also maintaining older titles.

3. IMDb rating analysis shows the overall quality distribution of movies and TV shows, with most titles concentrated around the middle-to-good rating range.

4. The highest-rated titles can help identify content that has received strong audience feedback.

5. TMDB popularity analysis highlights the titles receiving the highest level of audience interest.

6. Runtime analysis shows the most common duration range for movies available in the dataset.

7. Age-certification analysis shows the type of audience Amazon Prime's catalog is mainly suitable for.

8. Actor analysis identifies the actors appearing most frequently across titles in the dataset.

9. Director analysis identifies directors with the largest number of titles in the Amazon Prime catalog.

10. Overall, the analysis shows that Amazon Prime has a diverse catalog across movies, TV shows, release years, ratings, actors and directors.

**Recommendations**



Amazon Prime can focus on acquiring and promoting highly rated content to improve viewer satisfaction.

Popular titles should receive greater visibility through recommendations and promotional campaigns.

The platform can maintain a balanced mix of movies and TV shows to serve different viewing preferences.

Content with strong IMDb ratings and high TMDB popularity can be prioritized for homepage recommendations.

Audience certification and runtime preferences can be used to create more personalized content recommendations.

Popular actors and directors can also be used to create curated collections and attract viewers.

**Project Conclusion**

In this project, I analyzed the Amazon Prime Movies and TV Shows dataset using Python and Pandas.

I performed data loading, data understanding, data cleaning, exploratory data analysis and data visualization.

Plotly was used to create interactive visualizations for content type, release year, IMDb ratings, popularity, runtime, age certification, actors and directors.

The analysis helped identify important patterns in Amazon Prime's content library and provided useful insights into content distribution, ratings, popularity and talent.

This project demonstrates my basic skills in Python, Pandas, data cleaning, exploratory data analysis and data visualization.